trigger:
- none

steps:
- pwsh: dotnet build
- pwsh: dotnet test --collect:"XPlat Code Coverage"
- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: cobertura
    summaryFileLocation: test/MailApp.Tests/TestResults/**/coverage.cobertura.xml